name: BuildImage

on:
  push:
    branches: test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        uses: actions/checkout@v2

      - name: step2
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3

      - name: step3
        if: success() && github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: step4
      run: |
        docker buildx build --tag 2233466866/lnmp:test --platform linux/386,linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8 .